Recommend to use the latest version of Python
SheCodesAustralia/workshopcontent pull request #28
Opened 2023-09-09 05:09 UTC by Kai-Striega

The previously recommended version (3.5) reached EOL several *years* ago and is no longer available for download from the Python website.

This commit changes the recommended version to the latest version of Python - and gives a hint to the reader why it should be used.

2023-09-09 05:15 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> + Let's start by installing Python! We want you to install Python 3.11, however if you already have an earlier version installed that should work too!
```suggestion
 Let's start by installing Python! We want you to install the latest version of Python, however if you already have an earlier version installed that should work too!
```

I'm not sure if it would be better to say it like this, that way it won't have to be updated whenever a new version is released.

2023-09-11 07:40 UTC, bendog reviewed
some thoughts?

2023-09-11 07:40 UTC, bendog commented on content/python/getting_started/1_python_installation/_index.md
> +
I think we might still need to specify a lowest level requirement. 
We should probably also have instructions on how to check which version of python is installed. 

maybe something like 
> Let's start by checking if you have python installed, you'll need to have at least version 3.5 for this tutorial. 

if the students have already been introduced to the command line we could ask them to run `python --version` for windows and `python3 --version` for mac/linux. 

I think saying simply that "earlier version should work too" is a little misleading, as some people may have very old laptops which have system versions which might be before then.

2023-09-11 07:40 UTC, bendog commented on content/python/getting_started/1_python_installation/_index.md
> +
I like where this is going, it's good advice, but perhaps the audience for this advice is a later session. 
Right now this is just about getting the minimum requirements installed, let's not throw too much at them.

2023-09-11 07:43 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> +
Do we know that 3.5 still runs it? Apparently much of the code has recently been fixed up, it might be worth checking that first.

2023-09-11 07:51 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> +
I would even recommend a higher version as the minimum. Even if that isn't strictly required

2023-09-12 12:37 UTC, Hauteclere commented on content/python/getting_started/1_python_installation/_index.md
> +
I agree with both of you. Anything older than 3.8 is in end-of-life, so let's set that as the minimum? 

How about something like:

```md
We're finally here!

We need Python before we can start. If you don't have it installed yet, you can install the latest version (at the time of writing, that's 3.11.5) by following the instructions below. 

If you already have Python 3.8 or higher installed, you'll be able to use that. On the other hand, if you have a version older than 3.8, you should upgrade it. Older versions are considered "end-of-life".

{{% notice info %}}  
This section is based on [a tutorial by Geek Girls Carrots](https://github.com/ggcarrots/django-carrots).
{{% /notice %}}
```

We could probably also update the version numbers that are scattered throughout the Linux instructions, but they're just examples of what the terminal might spit out in response to commands, so it's probably lower priority.

2023-09-12 12:41 UTC, Hauteclere commented on content/python/getting_started/1_python_installation/_index.md
> +
Alternatively, here's what we currently have for the Plus program: https://github.com/SheCodesAus/PlusLessonContent/blob/main/Python/1_installing/1_installing.md

We can cannibalize as much of this as we need, although any references to Git Bash should probably be removed.

2023-09-12 12:44 UTC, Hauteclere commented on content/python/getting_started/1_python_installation/_index.md
> +
Interested to hear what you both think on this! 

@Kai-Striega, if you're available to amend the PR feel free. Or if you're busy, if you give me permission to push to your branch, I can apply any changes.

2023-09-12 13:08 UTC, bendog commented on content/python/getting_started/1_python_installation/_index.md
> +
> macOS used to come with Python 2.7 pre-installed between versions 10.8 and 12.3.

> Python is being deprecated from macOS 12.3 onward, and will no longer be preinstalled on the Mac.

Seems my concerns about old built in versions don't apply to Mac. They still apply to Linux. 

Code was updated by me to be 3.5+ only a couple of years ago, so yes, can confirm that 3.5 will work. 

I think it's best to avoid hard coding version numbers other than to say it needs to be 3.5+

2023-09-13 01:43 UTC, bendog requested changes
Quick comment on cli commands. 
need python3 for not-that-old Mac and Linux os

2023-09-13 01:52 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
`py` is the official *launcher* of Python on Windows - it should find the installed Python version. TBH I'm not that sure how Python on Windows works so I went with the officially recommended way.

Noted about `Python3` I'll fix that now

2023-09-13 01:56 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
Actually, I think we should remove the whole `py` thing. That way we stay consistent with the rest of the tutorial.

2023-09-13 03:20 UTC, bendog commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
Also there’s a sneaky .swp file

2023-09-13 05:40 UTC, Hauteclere commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
I have a feeling that users on windows might run into trouble with `python3` - the name that gets added to the path is generally just `python`, so from memory `python3` won't work unless they do the work to set it up as an alias. 

So if we cut out references to `py`, we'll need to replace it with `python`, unless either of you knows a better way. :)

2023-09-13 05:45 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
What if I change the line `if you are on Windows.` to `if you are on Windows and the python3 command doesn't work try py`

2023-09-13 10:44 UTC, bendog commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
does `py` work on all windows versions? 
does using `py` have advantages over `python`? 

i'm guessing if you use `py` then windows will go and look for python in the windows app store? 
is this the benefit? 
I think you're talking to a bunch of Mac people here, so we might not understand the benefits 😝

2023-09-13 14:52 UTC, jomarieminney commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
I have previously installed python on Windows and was running it tonight and Ross installed tonight on his Windows laptop from scratch. Let us know if you need testing done.

Also a comment - nobody ever knows what a terminal is, this needs more guidance. If they don't have a "terminal application of choice" on Windows they can use Powershell (or Command Prompt if they have a very old machine). Search Powershell in the start menu to open the app.

2023-09-18 04:29 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
> does py work on all windows versions?

It should do, as long as it's installed with Python. 

> does using py have advantages over python?

`py` uses the most recent version installed by default. It can also be used to launch venvs.

> i'm guessing if you use py then windows will go and look for python in the windows app store?

`py` will look for the most recent version of Python, regardless of the source. What I came across this weekend at the one-day workshop is that `python3` will look for it on the Microsoft store if it hasn't been added to PATH. This might need to be tested

> I think you're talking to a bunch of Mac people here, so we might not understand the benefits 😝

I agree, I haven't used windows for development in a while. It tripped me up.

> Also a comment - nobody ever knows what a terminal is, this needs more guidance. 

Thanks! I'll add that in.

2023-09-18 08:11 UTC, Kai-Striega commented
I'm going to have to do some thinking about how to phrase this. I'll hopefully have the time Wednesday to get done work done here.

2023-10-08 03:22 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> +
Although I've deleted this (for now) I think it would be good to have this included. At the one-day workshop, I had several participants ask me what version to install. I think it would be simpler to just have it written down.

2023-10-08 03:29 UTC, Kai-Striega commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
Some participants (maybe 2 to 3) had the problem that they couldn't use `python` on Windows and had to use `py` instead. I'm not what they set up differently. I think recommending `py` is better because:

* it's the officially recommended version
* it worked even when `python` didn't
* `py` is installed with every version of python post 3.3

As an aside, have we thought of recommending the version from the Microsoft store? From the Python docs:

> The Microsoft Store package is an easily installable Python interpreter that is intended mainly for interactive use, for example, by students.

I'm not exactly sure **how** it's different but it may be worth considering.

2023-10-08 10:32 UTC, Hauteclere commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
The Microsoft store version definitely has my support - that's what we're using in the Plus cohort right now. :)

2023-10-09 03:49 UTC, Hauteclere commented on content/python/getting_started/1_python_installation/_index.md
> +py --version
It looks like the `py` vs `python3` changes that were requested have been applied, so I'm going to resolve this change request and merge. I agree with @jomarieminney Jo that we could use more advice for students, but I'm happy for this to be included in a subsequent PR

2023-10-09 03:52 UTC, merged